language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install: pip install -e . python-coveralls
# # command to run tests
script: python setup.py test
after_success:
  - coveralls
notifications:
    email:
        - bubenkoff@gmail.com
        - oleg.podsadny@gmail.com
