language: python
sudo: false
# # command to run tests
script: make test
after_success:
  - make coveralls
branches:
    except:
        - /^\d/
notifications:
    email:
        - bubenkoff@gmail.com
        - oleg.pidsadnyi@gmail.com
